export { default as Add } from "./Add/add.svg"
export { default as AddPicture } from "./AddPicture/addPicture.svg"
export { default as ArrowBottom } from "./ArrowBottom/bottom.svg"
export { default as ArrowLeft } from "./ArrowLeft/left.svg"
export { default as ArrowRight } from "./ArrowRight/right.svg"
export { default as ArrowTop } from "./ArrowTop/top.svg"
export { default as ArrowTriangle } from "./ArrowTriangle/triangle.svg"
export { default as DateFlat } from "./DateFlat/dateFlat.svg"
export { default as DateLine } from "./DateLine/dateLine.svg"
export { default as Information } from "./Information/information.svg"
export { default as Search } from "./Search/search.svg"
export { default as Upload } from "./Upload/section.svg"
export { default as UserFlat } from "./UserFlat/userFlat.svg"
export { default as UserLine } from "./UserLine/userLine.svg"

